// 作品集数据
const portfolioData = {
    // 学校作品
    // 包装设计
    "packaging-1": {
        title: "高庙红薯包装 | 项山脐橙包装",
        category: "包装设计 | 2023",
        description: "这是高庙红薯和项山脐橙的包装设计项目，将水果与现代简约抽象设计相融合。创造出现代感的视觉效果。包装结构采用环保材料，便于回收利用，同时考虑了使用便捷性和产品保护性。",
        tools: ["Illustrator", "Photoshop"],
        images: [
            "img/academic/包装设计/包装设计.jpg",
            "img/academic/包装设计/0011.jpg",
            "img/academic/包装设计/0012.jpeg",
            "img/academic/包装设计/0013.png",

            "img/academic/包装设计/0021.jpg",
            "img/academic/包装设计/0022.jpeg",
            "img/academic/包装设计/0023.png",

            "img/academic/包装设计/0031.jpg",
            "img/academic/包装设计/0032.jpeg",
            "img/academic/包装设计/0033.png",

            "img/academic/包装设计/0041.jpg",
            "img/academic/包装设计/0051.jpg",
            "img/academic/包装设计/0061.jpg",
            "img/academic/包装设计/0071.jpg",
            "img/academic/包装设计/0081.jpg",
        ]
    },

    // 标识设计
    "creative-1": {
        title: "亿福康标识",
        category: "标识设计 | 2023",
        description: "为亿福康品牌设计的标识，亿福康是中医养生品牌，标识设计以中医养生为主题，采用传统中医元素，如鹤、葫芦等，融入现代设计理念，创造出独特而富有文化内涵的标识。",
        tools: ["Illustrator", "Photoshop", "C4D"],
        images: [
            "img/academic/标识设计/标识设计.jpg",
            "img/academic/标识设计/0011.jpg",
            "img/academic/标识设计/0012.jpg",
            "img/academic/标识设计/0021.jpg",
            "img/academic/标识设计/0031.jpg",
            "img/academic/标识设计/0032.jpg",
            "img/academic/标识设计/0033.jpg",
            "img/academic/标识设计/0034.jpg",
            "img/academic/标识设计/0041.jpg",
            "img/academic/标识设计/0042.jpg",
        ]
    },

    // 创意设计
    "logo-1": {
        title: "兔年日历创意",
        category: "创意设计 | 2023",
        description: "兔年日历创意设计，以兔年为主题，设计了两张兔年日历，与季节元素进行融合，设计风格简洁明朗，色彩鲜艳，富有创意。",
        tools: ["Illustrator", "Photoshop"],
        images: [
            "img/academic/创意设计/创意设计.jpg",
            "img/academic/创意设计/0011.jpg",
            "img/academic/创意设计/0021.jpg",
        ]
    },

    // 海报设计
    "poster-1": {
        title: "银鹭植物 | 电解制水",
        category: "海报设计 | 2023",
        description: "为银鹭植物与电解制水设计的海报，银鹭植物从'0'为出发点，用人物形态构建'0'的形态，体现产品特点。电解制水以植物为主题，用果汁围绕产品环绕，体现产品不同口味，设计风格简洁明朗，色彩鲜艳，富有创意。",
        tools: ["Photoshop", "Illustrator", "InDesign"],
        images: [
            "img/academic/海报设计/海报设计001.jpg",
            "img/academic/海报设计/海报设计002.jpg",
            "img/academic/海报设计/0011.jpg",
            "img/academic/海报设计/0012.jpg",
            "img/academic/海报设计/0013.jpg",
            "img/academic/海报设计/0021.jpg",
            "img/academic/海报设计/0022.jpg",
            "img/academic/海报设计/0023.jpg",
        ]
    },


    // 书籍设计
    "book-1": {
        title: "书籍设计",
        category: "书籍设计 | 2023",
        description: "河南豫剧：整理河南豫剧相关资料整和成一本书籍，详细讲解了河南豫剧的历史发展。设计学概论封面再设计：将设计学概论的封面进行再设计，采用了简约的设计风格。宣传手册：为黄淮学院设计的宣传手册，围绕黄淮学院校园风光进行展开设计。",
        tools: ["Photoshop", "Illustrator", "InDesign"],
        images: [
            "img/academic/书籍设计/书籍设计001.jpg",
            "img/academic/书籍设计/书籍设计002.jpg",
            "img/academic/书籍设计/书籍设计003.jpg",
        ]
    },

    // 信息可视化设计
    "infovis-1": {
        title: "信息可视化设计",
        category: "信息可视化设计 | 2023",
        description: "信息可视化设计，将抽象的数据通过可视化的方式展现出来，让数据更加直观，更加易于理解。",
        tools: ["Photoshop", "Illustrator", "InDesign"],
        images: [
            "img/academic/信息可视化/信息可视化.jpg",
            "img/academic/信息可视化/0011.png",
            "img/academic/信息可视化/0021.jpg",
            "img/academic/信息可视化/0031.png",
            "img/academic/信息可视化/0041.jpg",
            "img/academic/信息可视化/0051.jpg",
        ]
    },

    // 展示设计
    "exhibition-1": {
        title: "梵高",
        category: "展示设计 | 2023",
        description: "梵高展，以梵高为主题做了展示设计，采用了梵高画作的元素，配套有海报，3d场景等",
        tools: ["Photoshop", "Blender"],
        images: [
            "img/academic/展示设计/展示设计.jpg",
            "img/academic/展示设计/0011.jpg",
            "img/academic/展示设计/0012.jpg",
            "img/academic/展示设计/0021.jpg",
            "img/academic/展示设计/0022.jpg",
            "img/academic/展示设计/0023.jpg",
            "img/academic/展示设计/0024.jpg",
        ]
    },



    // 实习作品
    "shixi": {
        title: "实习作品",
        images: [
            "img/internship/001.jpg",
            "img/internship/002.jpg",
            "img/internship/003.jpg",
            "img/internship/004.jpg",
            "img/internship/005.jpg",
            "img/internship/006.jpg",
            "img/internship/007.jpg",
            "img/internship/008.jpg",
            "img/internship/009.jpg",
            "img/internship/010.jpg",
            "img/internship/011.jpg",
            "img/internship/012.jpg",
            "img/internship/013.jpg",
            "img/internship/014.jpg",
            "img/internship/015.jpg",
            "img/internship/016.jpg",
            "img/internship/017.jpg",
            "img/internship/018.jpg",
            "img/internship/019.jpg",
            "img/internship/020.jpg",
            "img/internship/021.jpg",
            "img/internship/022.jpg",
            "img/internship/023.jpg",
            "img/internship/024.jpg",
            "img/internship/025.jpg",
            "img/internship/026.jpg",
            "img/internship/027.jpg",
            "img/internship/028.jpg",
            "img/internship/029.jpg",
            "img/internship/030.jpg",
            "img/internship/031.jpg",
            "img/internship/032.jpg",
            "img/internship/033.jpg",
            "img/internship/034.jpg",
            "img/internship/035.jpg",
            "img/internship/036.jpg",
            "img/internship/037.jpg",
            "img/internship/038.jpg",
            "img/internship/039.jpg",
            "img/internship/040.jpg",
            "img/internship/041.jpg",
            "img/internship/042.jpg",
            "img/internship/043.jpg",
            "img/internship/044.jpg",
            "img/internship/045.jpg",
            "img/internship/046.jpg",
            "img/internship/047.jpg",
            "img/internship/048.jpg",
            "img/internship/049.jpg",
            "img/internship/050.jpg",
            "img/internship/051.jpg",
            "img/internship/052.jpg",
            "img/internship/053.jpg",
            "img/internship/054.jpg",
            "img/internship/055.jpg",
            "img/internship/056.jpg",
            "img/internship/057.jpg",
            "img/internship/058.jpg",
            "img/internship/059.jpg",
            "img/internship/060.jpg",
            "img/internship/061.jpg",
            "img/internship/062.jpg",
            "img/internship/063.jpg",
            "img/internship/064.jpg",
            "img/internship/065.jpg",
            "img/internship/066.jpg",
            "img/internship/067.jpg",
            "img/internship/068.jpg",
            "img/internship/069.jpg",
            "img/internship/070.jpg",
            "img/internship/071.jpg",
            "img/internship/072.jpg",
            "img/internship/073.jpg",
            "img/internship/074.jpg",
            "img/internship/075.jpg",
            "img/internship/076.jpg",
            "img/internship/077.jpg",
            "img/internship/078.jpg",
            "img/internship/079.jpg",
            "img/internship/080.jpg",
            "img/internship/081.jpg",
            "img/internship/082.jpg",
            "img/internship/083.jpg",
            "img/internship/084.jpg",
            "img/internship/085.jpg",
            "img/internship/086.jpg",
            "img/internship/087.jpg",
            "img/internship/088.jpg",
            "img/internship/089.jpg",
            "img/internship/090.jpg",
            "img/internship/091.jpg",
            "img/internship/092.jpg",
            "img/internship/093.jpg",
            "img/internship/094.jpg",
            "img/internship/095.jpg",
            "img/internship/096.jpg",
            "img/internship/097.jpg",
            "img/internship/098.jpg",
            "img/internship/099.jpg",
            "img/internship/100.jpg",
            "img/internship/101.jpg",
            "img/internship/102.jpg",
            "img/internship/103.jpg",
            "img/internship/104.jpg",
            "img/internship/105.jpg",
            "img/internship/106.jpg",
            "img/internship/107.jpg",
            "img/internship/108.jpg",
            "img/internship/109.jpg",
            "img/internship/110.jpg",
            "img/internship/111.jpg",
            "img/internship/112.jpg",
            "img/internship/113.jpg",
            "img/internship/114.jpg",
            "img/internship/115.jpg",
            "img/internship/116.jpg",
            "img/internship/117.jpg",
            "img/internship/118.jpg",
            "img/internship/119.jpg",
            "img/internship/120.jpg",
            "img/internship/121.jpg",
            "img/internship/122.jpg",
            "img/internship/123.jpg",
            "img/internship/124.jpg",
            "img/internship/125.jpg",
            "img/internship/126.jpg",
            "img/internship/127.jpg",
            "img/internship/128.jpg",
            "img/internship/129.jpg",
            "img/internship/130.jpg",
            "img/internship/131.jpg",
            "img/internship/132.jpg",
            "img/internship/133.jpg",
            "img/internship/134.jpg",
            "img/internship/135.jpg",
            "img/internship/136.jpg",
            "img/internship/137.jpg",
            "img/internship/138.jpg",
            "img/internship/139.jpg",
            "img/internship/140.jpg",
            "img/internship/141.jpg",
            "img/internship/142.jpg",
            "img/internship/143.jpg",
            "img/internship/144.jpg",
            "img/internship/145.jpg",
            "img/internship/146.jpg",
            "img/internship/147.jpg",
            "img/internship/148.jpg",
            "img/internship/149.jpg",
            "img/internship/150.jpg",
            "img/internship/151.jpg",
            "img/internship/152.jpg",
            "img/internship/153.jpg",
            "img/internship/154.jpg",
            "img/internship/155.jpg",
            "img/internship/156.jpg",
            "img/internship/157.jpg",
            "img/internship/158.jpg",
            "img/internship/159.jpg",
            "img/internship/160.jpg",
            "img/internship/161.jpg",
            "img/internship/162.jpg",
            "img/internship/163.jpg",
            "img/internship/164.jpg",
            "img/internship/165.jpg",
            "img/internship/166.jpg",
            "img/internship/167.jpg",
            "img/internship/168.jpg",
            "img/internship/169.jpg",
            "img/internship/170.jpg",
            "img/internship/171.jpg",
            "img/internship/172.jpg",
            "img/internship/173.jpg",
            "img/internship/174.jpg",
            "img/internship/175.jpg",
            "img/internship/176.jpg",
            "img/internship/177.jpg",
            "img/internship/178.jpg",
            "img/internship/179.jpg",
            "img/internship/180.jpg",
            "img/internship/181.jpg",
            "img/internship/182.jpg",
            "img/internship/183.jpg",
            "img/internship/184.jpg",
            "img/internship/185.jpg",
            "img/internship/186.jpg",
            "img/internship/187.jpg",
            "img/internship/188.jpg",
            "img/internship/189.jpg",
            "img/internship/190.jpg",
            "img/internship/191.jpg",
            "img/internship/192.jpg",
            "img/internship/193.jpg",
            "img/internship/194.jpg",
            "img/internship/195.jpg",
            "img/internship/196.jpg",
            "img/internship/197.jpg",
            "img/internship/198.jpg",
            "img/internship/199.jpg",
            "img/internship/200.jpg",
            "img/internship/201.jpg",
            "img/internship/202.jpg",
            "img/internship/203.jpg",
            "img/internship/204.jpg",
            "img/internship/205.jpg",
            "img/internship/206.jpg",
            "img/internship/207.jpg",
            "img/internship/208.jpg",
            "img/internship/209.jpg",
            "img/internship/210.jpg",
            "img/internship/211.jpg",
            "img/internship/212.jpg",
            "img/internship/213.jpg",
            "img/internship/214.jpg",
            "img/internship/215.jpg",
            "img/internship/216.jpg",
            "img/internship/217.jpg",
            "img/internship/218.jpg",
            "img/internship/219.jpg",
            "img/internship/220.jpg",
            "img/internship/221.jpg",
            "img/internship/222.jpg",
            "img/internship/223.jpg",
            "img/internship/224.jpg",
            "img/internship/225.jpg",
            "img/internship/226.jpg",
            "img/internship/227.jpg",
            "img/internship/228.jpg",
            "img/internship/229.jpg",
            "img/internship/230.jpg",
            "img/internship/231.jpg",
            "img/internship/232.jpg",
            "img/internship/233.jpg",
            "img/internship/234.jpg",
            "img/internship/235.jpg",
            "img/internship/236.jpg",
            "img/internship/237.jpg",
            "img/internship/238.jpg",
            "img/internship/239.jpg",
            "img/internship/240.jpg",
            "img/internship/241.jpg",
            "img/internship/242.jpg",
            "img/internship/243.jpg",
            "img/internship/244.jpg",
            "img/internship/245.jpg",
            "img/internship/246.jpg",
            "img/internship/247.jpg",
            "img/internship/248.jpg",
            "img/internship/249.jpg",
            "img/internship/250.jpg",
            "img/internship/251.jpg",
            "img/internship/252.jpg",
            "img/internship/253.jpg",
            "img/internship/254.jpg",
            "img/internship/255.jpg",
            "img/internship/256.jpg",
            "img/internship/257.jpg",
            "img/internship/258.jpg",
            "img/internship/259.jpg",
            "img/internship/260.jpg",
            "img/internship/261.jpg",
            "img/internship/262.jpg",
            "img/internship/263.jpg",
            "img/internship/264.jpg",
            "img/internship/265.jpg",
            "img/internship/266.jpg",
            "img/internship/267.jpg",
            "img/internship/268.jpg",
            "img/internship/269.jpg",
            "img/internship/270.jpg",
            "img/internship/271.jpg",
            "img/internship/272.jpg",
            "img/internship/273.jpg",
            "img/internship/274.jpg",
            "img/internship/275.jpg",
            "img/internship/276.jpg",
            "img/internship/277.jpg",
            "img/internship/278.jpg",
        ]
    },
}; 